config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :items do

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :find_item, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def show
  end

  def index
    @items = Item.all.where(enabled: true).sort_by { |i| i.id}
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :enabled, photos: [])
  end

  def find_item
    @item = Item.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 search_results">
      <%= simple_form_for [@item] do |f| %>
        <%= f.input :name, label: 'Item Name', input_html: { class: 'search-fields' }  %>
        <%= f.input :description, input_html: { class: 'search-fields' } %>
        <%= f.input :price, input_html: { class: 'search-fields' } %>
        <%= f.input :enabled, input_html: { class: 'search-fields' } %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <div class="mb-5">
      <%= f.submit "Add item", class: "btn search-button-styled mt-2 form-control", style: "width: 100%;" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1 class="text-center mt-4">Edit Item</h1>
<%= render "item_form" %>

app/views/items/home.html.erb
<div class="for-sale-sign">
  <p>For Sale</p>
</div>

<div class="my-container">

<% @items.each do |item| %>
<%= link_to item_path(item) do%>
  <div class="item-text">

  <% if item.photos.attached? %>
    <%= cl_image_tag item.photos.first.key, width: 300, height: 300, crop: :fill,  class: "", alt: "first slide" %>
  <% else %>
        <img src="https://picsum.photos/300" alt="">
  <% end %>
    <p><strong><%= item.name %></strong></p>
    <p><%= item.description %></p>
  </div>
<% end %>
<% end %>

</div>

app/views/items/index.html.erb
<header>
    <p class="intro-text" style="font-family: 'Open Sans', sans-serif;">Hey, I'm Victor.  These are things I'm selling in Mexico City, in <a href="https://goo.gl/maps/ucpN1GPYwdz4CMPw6" target="_blank">Azcapotzalco</a>.  I might be able to deliver some items.  You can contact me on <a href="https://wa.me/15107099748" target="_blank">Whatsapp</a>.  ✌️</p>
</header>

<div class="main-container mt-3" align="center">

<div class="cards">
      <% carouselNumber = 0 %>
      <% @items.each do |item| %>
      <div>
        <%= link_to item_path(item) do%>
          <div class="item-box text-left" style="position: relative;">
            <% if item.photos.attached? %>
              <% if item.photos.attached? %>
                <div style="max-width: 325px; position: relative;">
                   <div id="carousel<%= carouselNumber %>" class="carousel slide carousel-slider" data-ride="carousel" data-interval="false" data-touch="false">
                    <div class="carousel-inner rounded mb-1" style="width: 100%; height: 240px !important;">
                      <div class="carousel-item active" style="cursor: pointer !important">
                        <%= cl_image_tag item.photos.first.key, width: 640, height: 480, crop: :pad, class: "d-block w-100 h-100 carousel-img img-rounded", alt: "first slide" %>
                      </div>

                      <% item.photos.drop(1).each do |photo| %>

                        <div class="carousel-item" style="cursor: pointer !important">
                          <%= cl_image_tag photo.key, width: 640, height: 480, crop: :pad,  class: "d-block w-100 h-100 carousel-img img-rounded", alt: "a slide" %>
                        </div>
                      <% end %>
                    </div>
                    <% if item.photos.length > 1 %>
                    <a class="carousel-control-prev" href="#carousel<%= carouselNumber %>" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <% end %>
                    <% if item.photos.length > 1 %>
                    <a class="carousel-control-next" href="#carousel<%= carouselNumber %>" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                    <% end %>
                  </div>
                </div>
                <% carouselNumber += 1 %>
                 <!-- <%= cl_image_tag item.photos.first.key, width: 325, height: 240, crop: :pad,  class: "img-rounded", alt: "first slide" %> -->
              <% end %>

            <% else %>
              <img src="https://res.cloudinary.com/vc334/image/upload/v1615245363/No_image_available_xvmu8r.svg" class="imgTest" alt="" style="width: 325px; height: 240px;">
            <% end %>
            <% if item.photos.count > 1 %>
              <div class="image-counter display-image-count text-rounded" data-count="<%= item.photos.count %>">image 1 of <%= item.photos.count %></div>
            <% end %>
            <%= link_to item_path(item) do%><p class="item-name"><span class="item-name-underline"><%= item.name %></span><% end %><span class="price">$<%= item.price %></span></p>
            <p class="price corner-price">$<%= item.price %></p>
          </div>
        <% end %>
      </div>
      <% end %>
<!--
              <% if @items.length % 3 != 0  %>
          <div class="hide-this" style="width: 323px; height: 323px; display: hidden"></div>
        <% end %> -->
    </div>

</div>


<%= javascript_pack_tag 'carousels' %>
<%= javascript_pack_tag 'index' %>

app/views/items/new.html.erb
<div class="container menu pt-3">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <div class="show text-center mb-3">
      <h1>Add a Food Stall</h1>
      </div>

<%= render "item_form" %>

    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container show-container mt-4 p-4" style="min-height: 620px">
  <% if @item.enabled == false %>
    <h1>Sorry, this item is either not currently for sale or has been sold.</h1>
  <% else %>
  <h1><%= @item.name %> - $<%= @item.price %></h1>
  <div class="row">
    <div class="col-lg-5">
      <% if @item.photos.attached? %>
        <div style="max-width: 400px;">
          <% if @item.photos.count > 1 %>
            <div class="carousel-image-counter" data-count="<%= @item.photos.count %>">image 1 of <%= @item.photos.count %></div>
            <% else %>
            <div class="carousel-image-counter" style="opacity: 0;" data-count="<%= @item.photos.count %>">image 1 of <%= @item.photos.count %></div>
          <% end %>

          <div id="carouselExampleControls" class="carousel slide carousel-slider" data-ride="carousel" data-interval="false" data-touch="false">
            <div class="carousel-inner rounded show-carousel" style="width: 100%">
              <div class="carousel-item active">
                <%= cl_image_tag @item.photos.first.key, width: 800, height: 800, crop: :pad, class: "d-block w-100 h-100 carousel-img", alt: "first slide", "data-count": "1" %>
              </div>
              <!-- 400 400  -->
              <% photoCount = 2  %>
              <% @item.photos.drop(1).each do |photo| %>
                <div class="carousel-item">
                  <%= cl_image_tag photo.key, width: 800, height: 800, crop: :pad,  class: "d-block w-100 h-100 carousel-img", alt: "a slide", "data-count": "#{photoCount}" %>
                </div>
                <% photoCount += 1 %>
              <% end %>
            </div>
            <% if @item.photos.length > 1 %>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            <% end %>
          </div>
        </div>
      <% end %>
        <% if @item.photos.attached? && @item.photos.length > 1 %>
          <div class="mb-2 mt-1">
            <% the_num2 = 0 %>
            <% @item.photos.take(10).each do |photo| %>
              <%= cl_image_tag photo.key, width: 70, height: 70, class: "thumbnail", style:"border-radius: 6px; object-fit: cover;", :data => { :count => "#{the_num2}" }%>
              <% the_num2 += 1 %>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-lg-7">
      <p class="mt-3"><%= @item.description %></p>
      <p><strong><a class="whatsapp-link" href="https://wa.me/15107099748" target="_blank">Contact me on Whatsapp</a></strong></p>
      <% if current_user == @item.user %>
        <%= link_to "Edit", edit_item_path(@item) %>
        <%= link_to "Delete", item_path(@item), method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>
    </div>
 </div>
</div>

<div class="modal">
  <div class="modalInner">
    <i class="fas fa-times-circle modal-close-button"></i>
    <% if @item.photos.count > 1 %>
      <div class="modal-image-counter top-level" style="opacity: 0.7 !important" data-count="<%= @item.photos.count %>">image 1 of <%= @item.photos.count %></div>
    <% end %>
    <% if @item.photos.length == 1 %>
      <button aria-label="Previous Photo" class="prev hidden-opacity"><</button>
    <% else %>
      <button aria-label="Previous Photo" class="prev"><</button>
    <% end %>
    <figure>
      <% if @item.photos.count > 0 %>
      <%= cl_image_tag @item.photos.first.key, width: 800, height: 800, crop: :pad, alt: "first slide" %>
      <% end %>
      <figcaption>
        <h2>Test Title</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor dignissimos obcaecati nisi placeat eaque
          voluptate, exercitationem eius? Non, iusto provident itaque, voluptate labore a alias officia, amet sunt
          pariatur praesentium tenetur voluptatibus dolores mollitia quasi aliquid assumenda possimus maiores
          exercitationem!</p>
      </figcaption>
    </figure>
    <% if @item.photos.length == 1 %>
      <button class="next hidden-opacity" aria-label="Next Photo">></button>
    <% else %>
      <button class="next" aria-label="Next Photo">></button>
    <% end %>


  </div>
  <% end %>
</div>

<%= javascript_pack_tag 'carousel' %>
<%= javascript_pack_tag 'modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stuff For Sale</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="../../base.css"> -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- <%= render 'shared/navbar' %> -->
    <%= render 'shared/flashes' %>
    <div class="for-sale-sign mb-4">
      <%= link_to root_path do %>
      <p style="font-size: 2.5vw; opacity: 0.8; padding: 0 1rem;">Stuff For Sale</p>
      <% end %>
    </div>

    <%= yield %>
<!--     <footer>
      <span>© 2020 Victor Chiang</span>
    </footer> -->
    <%= yield(:carousel) %>
    <%= yield(:modal) %>
    <%= yield(:carousels) %>
    <%= yield(:index) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to current_user.email, "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>